apiVersion: v1
kind: PersistentVolume
metadata:
  name: dual-core-snapshot-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: general-storage-class
  local:
    path: /data/dual-core-snapshot
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: persistent_data
              operator: In
              values:
                - all
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dual-core-snapshot-pvc
spec:
  storageClassName: general-storage-class
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-core-snapshot
  labels:
    app: dual-core-snapshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-core-snapshot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dual-core-snapshot
      annotations:
        description: "Snapshot dual core daily"
    spec:
      containers:
        - name: dual-core-snapshot
          image: easyprompt2023/dual-core-snapshot:latest
          command: ['node']
          args: ['dist/main.js']
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: MONGO_URL
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: RPC_URL
            - name: DUAL_CORE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: DUAL_CORE_ADDRESS
            - name: CORE_VAULT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: CORE_VAULT_ADDRESS
            - name: SAVE_POINT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: SAVE_POINT_ENDPOINT
            - name: SAVE_POINT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: dual-core-snapshot
                  key: SAVE_POINT_PRIVATE_KEY
          volumeMounts:
            - mountPath: "/home/node/app/volumes"
              name: dual-core-snapshot-volumes
      imagePullSecrets:
        - name: cred-docker-hub
      volumes:
        - name: dual-core-snapshot-volumes
          persistentVolumeClaim:
            claimName: dual-core-snapshot-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dual-core-snapshot-service
spec:
  selector:
    app: dual-core-snapshot
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
